FROM node:lts AS development

WORKDIR /app

# 1. First copy package.json and yarn.lock (for caching)
COPY package.json package-lock.json ./

# 2. Install all dependencies (including devDependencies)
RUN npm install --frozen-lockfile --production=false

# 3. Copy the rest of the app
COPY . .

# 4. Expose the port (if your app runs on 3010)
EXPOSE 3010

# 5. Run in development mode (with Hot Reload)
CMD ["npm", "run", "dev"]

